# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
      timezone: "Australia/Sydney"

  - package-ecosystem: "pip"
    directory: "gcp/appengine/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    groups:
      - "appengine-backend"

  - package-ecosystem: "npm"
    directory: "gcp/appengine/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    groups:
      - "appengine-frontend"
  
  - package-ecosystem: "bundler"
    directory: "gcp/api/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    groups:
      - "api"
    ignore:
      - "grpcio*"
 
  - package-ecosystem: "bundler"
    directory: "gcp/functions/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    groups:
      - "functions"

  - package-ecosystem: "pip"
    directory: "docker/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    groups:
      - "workers"

  - package-ecosystem: "gomod"
    directory: "docker/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    groups:
      - "indexer"
 
  - package-ecosystem: "bundler" 
    directory: "vulnfeeds/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    groups:
      - "vulnfeeds"
  
  - package-ecosystem: "npm"
    directory: "docs/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    groups:
      - "docs"

  - package-ecosystem: "bundler"
    directory: "tools/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    groups:
      - "tools"

  - package-ecosystem: "terraform"
    directory: "deployment/terraform/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    groups:
      - "terraform"

  - package-ecosystem: "github-actions"
    directory: ".github/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    groups:
      - "workflows"

  - package-ecosystem: "pip"
    directory: "/" # Assuming pyproject.toml is at the root
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    groups:
      - "osv-lib"
    commit-message:
      prefix: "workflows"
