# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "gcp/appengine/"
      - "gcp/api/"
      - "gcp/functions/pypi/"
      - "docker/worker"
      - "tools/datafix"
      - "tools/api-performance-test/"
      - "vulnfeeds/tools/debian/debian_converter/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "grpcio*"
      - dependency-name: "python"
    groups:
      major-updates:
        update-types:
         - "major"
      minor-patch-updates:
        update-types:
         - "minor"
         - "patch"

  - package-ecosystem: "npm"
    directories:
      - "gcp/appengine/frontend3/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    groups:
      major-updates:
        update-types:
         - "major"
      minor-patch-updates:
        update-types:
         - "minor"
         - "patch"
  
  - package-ecosystem: "bundler"
    directory: "docs/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    groups:
      major-updates:
        update-types:
         - "major"
      minor-patch-updates:
        update-types:
         - "minor"
         - "patch"

  - package-ecosystem: "gomod"
    directories:
     - "docs/"
     - "vulnfeeds/"
     - "docker/indexer/"
     - "tools/datastore-remover/"
     - "tools/indexer-api-caller/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    groups:
      major-updates:
        update-types:
         - "major"
      minor-patch-updates:
        update-types:
         - "minor"
         - "patch"

  - package-ecosystem: "terraform"
    directory: "deployment/terraform/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    groups:
      major-updates:
        update-types:
         - "major"
      minor-patch-updates:
        update-types:
         - "minor"
         - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Sydney"
    labels:
      - "dependencies"
    groups:
      major-updates:
        update-types:
         - "major"
      minor-patch-updates:
        update-types:
         - "minor"
         - "patch"
